### ISSUE TITLE
as a reader I would like to know about the 'Change' trickery in two way bindings

### ISSUE THREAD

**Issue by bennett000** [rangle/ngCourse2#110]
Form [the docs](https://angular.io/docs/ts/latest/guide/cheatsheet.html)

> Sets up two-way data binding. Equivalent to: <my-cmp [title]="name" (titleChange)="name=$event">

title vs titleChange is not spelled out (to my knowledge) in our docs.

**Comment by e-schultz** [comment]
I was playing around with a plunker on this a few days ago, [link](https://plnkr.co/edit/FQNPHj0ApIi8gDaKrurt?p=preview)

Basically, if your component has input/output naming convention like

```js
export default class SomeComponent {
@Input() someThing: string;
@Output() someThingChange = new EventEmitter();
}
```

You can setup two way binding with

```html
<some-component [(someThing)]="myValue"></some-component>
```

If you want to do something else in addition to syncing up myValue, you can mix/match. 

```html
<some-component [(someThing)]="myValue" (someThingChange)="doExtraStuff($event)"></some-component>
```
So if you want to keep the value in sync, but maybe do some other stuff as a result - can still do both.

Fleshing out the two-way binding card to include a bit of this would be good.

**Comment by bennett000** [comment]
That looks good.  Varun also has an example that shows this off in the "pizza form".
