### ISSUE TITLE
DI View Bindings Example

### ISSUE THREAD

**Issue by bennett000** [rangle/ngCourse2#125]
@sumitarora brought to my attention the concept of view bindings.  The tl;dr is that it's possible to bind a dependency to a particular component _and_ have that dependency only accessible by its bound component.

We need to update the DI section with an example to reflect this.  Sumit has an example in the works.

**Comment by e-schultz** [comment]
@bennett000 @sumitarora according to [the docs](https://angular.io/docs/ts/latest/api/core/ComponentMetadata-class.html#!#sts=constructor(%7Bselector,%20inputs,%20outputs,%20properties,%20events,%20host,%20exportAs,%20moduleId,%20bindings,%20providers,%20viewBindings,%20viewProviders,%20changeDetection%20=%20ChangeDetectionStrategy.Default,%20queries,%20templateUrl,%20template,%20styleUrls,%20styles,%20directives,%20pipes,%20encapsulation%7D%3F:%20%7B%20selector%3F:%20string,%20input) the `viewBindings?:any[]` is being deprecated. Should this be about `  viewProviders?: any[],` ?

**Comment by bennett000** [comment]
Unfortunately I have not dug into this issue since @sumitarora brought it to my attention.  Do you have any info Sumit?

**Comment by jamesbs** [comment]
`viewBindings` has been renamed to `viewProviders` so this example would be about `viewProviders`. see https://github.com/angular/angular/issues/7564.

**Comment by bennett000** [comment]
@jamesbs do we need to add a new example for this, or change an existing one?  Sorry I'm not 100% clear.
