### ISSUE TITLE
TypeScript Section needs `type` keyword and fat arrow function types

### ISSUE THREAD

**Issue by bennett000** [rangle/ngCourse2#145]

**Comment by barretodavid** [comment]
"Type" Keyword: https://www.typescriptlang.org/docs/handbook/advanced-types.html

**Comment by turbobeast** [comment]
Fat Arrow functions are covered in the ES6 section. Besides the syntax of adding types, they really have no typescript-specific behaviour. Could get into `noImplicitThis`, but that is not specific to arrow functions. 

However, I do think the coverage of functions in typescript is lacking. It doesn't even mention shorthand for instance members in class constructors.

**Comment by turbobeast** [comment]
Nevermind... I see now that it is `fat arrow function TYPES`... I still think that coverage of functions in typescript is lacking.
