### ISSUE TITLE
es6 examples do not always transpile correctly

### ISSUE THREAD

**Issue by bennett000** [rangle/ngCourse2#149]
Notably the block scoped examples get transpiled incorrectly and don't work.  The code works natively in chrome.  It's also worth checking if wrapping in a function fixes that particular example.  There's some issues with the "module" being treated as global scope, and `let`/`const` [do not pollute the global scope](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/let "Let")

> At the top level of programs and functions, let, unlike var, does not create a property on the global object. For example:

**Comment by SethDavenport** [comment]
Didn't see this before I logged #168
