### ISSUE TITLE
Enterprises With Strict Firewalls Block Examples

### ISSUE THREAD

**Issue by bennett000** [rangle/ngCourse2#153]
So far in one instance our Observer example was blocked by a firewall.  We re-wrote the example on the fly to use GitHub's API instead.  This is not a huge problem but it's worth mentioning since we might have other enterprise clients with restrictive firewalls.  Since they need GitHub for npm installs etc it seems like it might be more consistent?

I have a rough draft of a GitHub version.

**Comment by jamesbs** [comment]
Closing this for now. May re-open if the need resurfaces.
