### ISSUE TITLE
Webinar: Intro to Angular 2 Components

### ISSUE THREAD

**Issue by SethDavenport** [rangle/ngCourse2#175]

**Comment by SethDavenport** [comment]
Doing this Monday the 25th. Outline here: http://go.rangle.io/webinar-intro-to-angular2-components

Don't think Varun is actually doing this one, just me.

**Comment by SethDavenport** [comment]
* [ ] Publish Outline
* [ ] Prepare slides
* [ ] Dry Run

**Comment by gillianml** [comment]
@SethDavenport 
FYI I changed this label from "webinar-series" to "ad-hoc"  and I hope this is ok with you.

The April 25th webinar http://go.rangle.io/webinar-intro-to-angular2-components will be a separate event from the May/June Angular 2 webinar series. 

So I though it would be worthwhile having different labels to improve clarity.

**Comment by SethDavenport** [comment]
Sure, makes sense, thanks.
