### ISSUE TITLE
Pick and Validate a markdown solution

### ISSUE THREAD

**Issue by gillianml** [rangle/ngCourse2#176]
Pick and validate a markdown solution for slides for the Angular 2 Webinar Series.

AC: (Thanks Seth!)
- course developers can write slides in Markdown
- the slides should be theme-able enough for marketing

**Comment by gillianml** [comment]
Hi @bertrandk, Last Wednesday, the support team met to identify what we need to do put together the May Angular 2.0 Webinar/Training Series. One action item we agreed upon was picking and validating a markdown solution for the slides.

Would it be possible for you to share your finding here?  Thanks!

**Comment by SethDavenport** [comment]
Talked with Betrand and this seems like a good solution: http://gnab.github.io/remark

**Comment by SethDavenport** [comment]
I'll make a PR with a sample setup as I work on Monday's ad-hoc webinar.  We'll need some help from Marketing with styling ideas.
