### ISSUE TITLE
Outline for Presenter Notes + Pick Live Coding Examples: Forms

### ISSUE THREAD

**Issue by gillianml** [rangle/ngCourse2#197]
Acceptance Criteria:
- An outline for presenter notes.
- Enough detail so that the presenter can estimate the effort to complete the content.
- Live Coding Examples picked

The webinar will be 2 hours in duration:
- 45 minutes presentation
- 45 minutes live coding
- 15 minutes Q&A

Draft outline from April 11 Online Training Discussion
Template driven approach to forms
Programmatic forms, explicit and “list”
Validation, built-in, custom, async
Observables
Styling forms - pristine, valid, …
Http
Testing Forms

https://docs.google.com/document/d/19o5H_yOB5_08r4bbT67Y3S-u4hVz6U0l6_boaUSqzmA/edit

**Comment by e-schultz** [comment]
re-formatting as webinars seems to be off the table now, closing.
