### ISSUE TITLE
Outline for Presenter Notes + Pick Live Coding Examples: Routes

### ISSUE THREAD

**Issue by gillianml** [rangle/ngCourse2#198]
Acceptance Criteria:
- An outline for presenter notes.
- Enough detail so that the presenter can estimate the effort to complete the content.
- Live Coding Examples picked

The webinar will be 2 hours in duration:
- 45 minutes presentation
- 45 minutes live coding
- 15 minutes Q&A

Draft Outline from April 11 Online Training Discussion
Basic Angular 1.x Style config
Lazy routes
Mountable / self contained child routes
Routing life cylce hooks
Routing parameters and state
Passing configured data in routes
Async routes?
Router outlets + multiple outlets
Containers vs. “stateless” components

https://docs.google.com/document/d/19o5H_yOB5_08r4bbT67Y3S-u4hVz6U0l6_boaUSqzmA/edit

**Comment by e-schultz** [comment]
Possible complication with this - angular RC has a new 'new' router with an API - the current routing material is for a router that will be deprecated. 

Do we:

* Do a presentation on a router that is soon to be deprecated (proably bad)
* Do a presentation on the new 'new' router - of which is an unstable API subject to breaking changes (slightly less bad) 

If doing it for the new-new router -> will also take more time to prepare, as it's not just re-using content that we have, it will require the generation of new content.

**Comment by e-schultz** [comment]
re-formatting as webinars seems to be off the table now, closing.
