### ISSUE TITLE
pipes take several arguments instead of an array of arguments -- update to handouts required

### ISSUE THREAD

**Issue by mdegani** [rangle/ngCourse2#223]
Custom pipes now take multiple arguments.  To pass several arguments into a pipe, separate them with `:`'s.  The following section should be updated: http://ngcourse.rangle.io/handout/pipes/custom_pipes.html.

I am making this change to the pipes exercise, but the gitbook will also have to be updated.

Changelog reference: https://github.com/angular/angular/blob/master/CHANGELOG.md#200-beta16-2016-04-26

**Comment by jamesbs** [comment]
This has been addressed in #219 and #229 can you review the PR to see if any further changes need to be made afterwards?

**Comment by mdegani** [comment]
👍
