### ISSUE TITLE
'Getting the Code' section out of date.

### ISSUE THREAD

**Issue by ssayan** [rangle/ngCourse2#245]
This entire section seems to be out of date: 

https://github.com/rangle/ngCourse2/blob/master/handout/tooling/getting_the_code.md

Looks like we're no longer following the YYYY-DD-MM format with workshop branches, and it's my understanding we may not be using `npm install` as well?

**Comment by bennett000** [comment]
@e-schultz @winkerVSbecks if i recall correctly most of the getting the code is out of date?  I'm wondering if something got added back for the workshops?  Can we remove/refactor this?

**Comment by winkerVSbecks** [comment]
Yea, we mostly use the exercise section now. The app is only used if we are doing a workshop.

**Comment by jamesbs** [comment]
Is this still relevant or can this be closed?

**Comment by e-schultz** [comment]
this can be closed, no longer relevant
