### ISSUE TITLE
no live-preview of example http://ngcourse.rangle.io/handout/di/angular2/the_injector_tree.html

### ISSUE THREAD

**Issue by alexeigo** [rangle/ngCourse2#263]

**Comment by gillianml** [comment]
@alexeigo ,  is this isolated to ePub?  When I click on "view example" in the gitbook, I see the plunkr example OK. If yes, let's label this issue "ePub"

**Comment by SethDavenport** [comment]
We're moving away from the live previews because they don't work well in the PDF and mobile formats. Links are better in this case.
