### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by mdegani** [rangle/ngCourse2#28]
File 01-features.md line 556 `this.toppings = toppings';` should be `this.toppings = 'toppings'`;
File 01-features.md line 937 `let set = [2, 3, 5, 7, 11];` (it was suggested that 'set' could be a different word).
File 05-di.md line 151 `Hambuerger` should be `Hamburger`.

**Comment by SethDavenport** [comment]
@mdegani, @steven-ks feel free to submit PRs for stuff like this :)

**Comment by SethDavenport** [comment]
It seems that these have all been fixed already.
