### ISSUE TITLE
errors on the build process

### ISSUE THREAD

**Issue by MichaelLSmith** [rangle/ngCourse2#280]
after running npm install in the app directory, I tried running npm run dev. I get all these errors after the last successful line 497. Am I missing something obvious?

 [497] ./~/redux-logger/lib/index.js 8.49 kB {1} [built] -- worked
ERROR in /home/michael/git/rangle_angular2/ngCourse2/app/src/mocks/mock-router-provider.ts
(41,7): error TS2346: Supplied parameters do not match any signature of call target.

ERROR in ./src/components/task-edit/task-edit.ts
(8,3): error TS2305: Module '"/home/michael/git/rangle_angular2/ngCourse2/app/node_modules/@angular/common/index"' has no exported member 'FORM_BINDINGS'.

ERROR in ./src/components/task-edit/task-edit.ts
(20,3): error TS2345: Argument of type '{ selector: string; directives: (typeof RouterLink | any[])[]; viewBindings: any[]; template: any...' is not assignable to parameter of type '{ selector?: string; inputs?: string[]; outputs?: string[]; properties?: string[]; events?: strin...'.
  Object literal may only specify known properties, and 'viewBindings' does not exist in type '{ selector?: string; inputs?: string[]; outputs?: string[]; properties?: string[]; events?: strin...'.

ERROR in ./src/components/task-add/task-add.ts
(4,3): error TS2305: Module '"/home/michael/git/rangle_angular2/ngCourse2/app/node_modules/@angular/common/index"' has no exported member 'FORM_BINDINGS'.

ERROR in ./src/components/task-add/task-add.ts
(16,3): error TS2345: Argument of type '{ selector: string; directives: (typeof RouterLink | Type[])[]; viewBindings: any[]; template: an...' is not assignable to parameter of type '{ selector?: string; inputs?: string[]; outputs?: string[]; properties?: string[]; events?: strin...'.
  Object literal may only specify known properties, and 'viewBindings' does not exist in type '{ selector?: string; inputs?: string[]; outputs?: string[]; properties?: string[]; events?: strin...'.

ERROR in ./src/components/login/login.ts
(4,3): error TS2305: Module '"/home/michael/git/rangle_angular2/ngCourse2/app/node_modules/@angular/common/index"' has no exported member 'FORM_BINDINGS'.
webpack: bundle is now VALID.

**Comment by e-schultz** [comment]
@MichaelLSmith thanks for pointing this out, there were some changes in RC2 that broke things, and we were not locking down the version to RC1. 

If you change the angular 2 dependencies to specifically RC 1, ie: `"@angular/common": "2.0.0-rc.1",` and re-install the node modules, it should fix the issue. We will update the app soon however to account for the RC2 changes

**Comment by e-schultz** [comment]
@MichaelLSmith should be resolved now
