### ISSUE TITLE
Template Driven Forms

### ISSUE THREAD

**Issue by e-schultz** [rangle/ngCourse2#517]
* New forms still allows for template driven forms
* Update content / examples / exercises

**Comment by bennett000** [comment]
@barretodavid I know you're not on this card but I think you've worked with these a little bit.  If you have capacity would you be able to add a list of things you think the forms chapter should discuss.  Also I know @danielfigueiredo has been working with forms extensively, but I'm not sure if he's used the newer ones.  

There may be other Ranglers who have been playing with the new forms too and their feedback is welcome.

**Comment by danielfigueiredo** [comment]
I quite familiar with the new forms too, let me you if I can help you with anything @barretodavid =]

**Comment by barretodavid** [comment]
I read the proposed API changes for the forms components a couple of weeks ago but I haven't used that extensively on my project. Still, I might be able to help. @danielfigueiredo and I can discuss some topics of interest to add to the chapter. The first one that I can think of is how to dynamically build forms from objects. That is a common problem that wasn't easy to solve before.
