### ISSUE TITLE
New Redux Example & Exercise

### ISSUE THREAD

**Issue by e-schultz** [rangle/ngCourse2#524]
Current hands-on for Redux is a little more complex/convoluted than it should be.

* [ ] - Come up with new exersice(s) 
* [ ] - Create hands-on section with instruction
* [ ] - Create solution folder

**Comment by mdegani** [comment]
Here is a link to a plunker which is the same as the new exercises in PR #610 -- it uses ng2-redux v3.2.0.  In case it helps when we get to updating the content in the book. https://plnkr.co/edit/7sGpGlj6tQnF0yPmLlmW?p=preview
