### ISSUE TITLE
Rework testing toolchain overview

### ISSUE THREAD

**Issue by jamesbs** [rangle/ngCourse2#592]
The testing toolchain overview page is great defining what role each tool plays in the testing stack but it's a bit much to digest. It might benefit from being reorganized or dressed up with something like icons to so people don't just tune out.

Connected to #744

**Comment by SethDavenport** [comment]
I would actually like us to rework this section to not use chai and sinon.  They are unnecessary with Jasmine, which provides its own spying and expectation syntax.

**Comment by clbond** [comment]
This is resolved by this PR: https://github.com/rangle/ngCourse2/pull/889
