### ISSUE TITLE
Update Unit Testing section to reflect RC4

### ISSUE THREAD

**Issue by e-schultz** [rangle/ngCourse2#620]
RC4 introduced some changes to unit testing.

https://github.com/angular/angular/blob/master/CHANGELOG.md

Main changes:

* beforeEachProviders has been removed
* injectAsync has been removed

Changelog gives decent before/after examples - our content should be updated to reflect those changes.

**Comment by SethDavenport** [comment]
Also, you no longer need to import `it`, `describe`, `beforeEach`, `expect` etc. from `@angular/core/testing`. Just use the raw Jasmine ones instead.

**Comment by e-schultz** [comment]
This has been covered in RC5/RC6 prep changes - closes #620
