### ISSUE TITLE
Cover Application Modules

### ISSUE THREAD

**Issue by e-schultz** [rangle/ngCourse2#631]
Change coming RC5,

https://docs.google.com/document/d/13-LUm1QvOff2631tHz6C4goIHuMzma2_1_PFiLryoIs/edit

Might be worth trying to prep this content before RC5 is released -

**Comment by e-schultz** [comment]
RC5 is out, and documentation on NgModule is now available

* https://angular.io/docs/ts/latest/guide/ngmodule.html
* https://angular.io/docs/ts/latest/api/core/index/NgModuleMetadata-class.html

There is allot to potentially cover with NgModule - instead of trying to cover every possible thing - should focus on the 'minimum to have an understanding of it'

**Comment by barretodavid** [comment]
`NgModule` is a topic that is now covered in the book
