### ISSUE TITLE
Add section covering named router outlets

### ISSUE THREAD

**Issue by andrewlo** [rangle/ngCourse2#637]
We need to add a section to the routing chapter on having multiple named router outlets

**Comment by andrewlo** [comment]
Had some trouble getting example working where you can navigate the named router without setting the main router: http://plnkr.co/edit/NvwYTeA1inyn307yQ4iJ?p=preview . May need to wait until next router release

**Comment by e-schultz** [comment]
Angular 2 RC5 /  Router 3 - RC1 now supports aux routes in the `RouterLink` DSL - may be worth investigating again soon.

**Comment by e-schultz** [comment]
closing in favour of #675
