### ISSUE TITLE
Update form exercises to the reactive forms

### ISSUE THREAD

**Issue by e-schultz** [rangle/ngCourse2#639]
The actual exercises are fine, but should be updated to RC4 using the Reactive Forms.

**Comment by smithad15** [comment]
Note that the old forms API is being referenced in `8.1.5 Using Observables From Other Sources`. The valueChanges observable in the example has been replaced with FormControl.registerOnChange()

**Comment by smithad15** [comment]
In regards to my previous comment on valueChanges no longer being a part of the new forms API, I was wrong. I was thrown by the fact that valueChanges is part of the AbstractControl class which FormGroup extends. It does, in fact, exist however does not show up in the angular.io API docs. Please disregard my previous comment in full.

**Comment by bennett000** [comment]
I feel like this card is done... we can re-open it if I am wrong
