### ISSUE TITLE
Self Closing Tags

### ISSUE THREAD

**Issue by imsingh** [rangle/ngCourse2#640]
Angular 2 is not currently supporting self closing tags. But on 67th page of book, it shows a HTML Snippet with self closing tags.

**Comment by bennett000** [comment]
We will be fixing this and adding an explicit note at the start of our templates section about this.

**Comment by watrool** [comment]
@bennett000 @imsingh Where are these tags? We changed the book a lot and current 67th page does not have any code snippet.
