### ISSUE TITLE
Update DI section to cover RC5/NgModule

### ISSUE THREAD

**Issue by e-schultz** [rangle/ngCourse2#674]
Things to cover:
* providers in an `@NgModule` get application scoped`
* the `provide` method is getting deprecated, and should be using the object literal instead.

e.g) in 'injection beyond classes',

```js
// before

provide(Hamburger, { useClass: Hamburger })

// after

{ provide: Hamburger, useClass: Hamburger }
```

* content in section should move away from `bootstrap` and to using `@NgModule`
* examples should be updated to use `@NgModule`
* While we are at it, update examples to follow [angular.io styleguide](https://angular.io/styleguide) for naming conventions/structure

**Comment by smithad15** [comment]
Note that the root (app) module injector is not the same as the root component injector. This has been erroneously stated in `9.1.3.3 The Injector Tree`

**Comment by bennett000** [comment]
I would also add that lazy loading has a number of implications with respect to the injectors.
