### ISSUE TITLE
Review ngMigrate section

### ISSUE THREAD

**Issue by e-schultz** [rangle/ngCourse2#676]
- Haven't really touched or looked at the ngMigrate section in awhile
- Do we still want to have this as part of the book?
- If so, need to update/review to see what changes if any are needed to cover RC5/release

**Comment by winkerVSbecks** [comment]
This might be something we can remove from the book. Need to confirm with Yuri, marketing, etc.

**Comment by barretodavid** [comment]
I agree with removing this section from the book. Most of the transition from Angular 1 to 2 that I'm aware of are complete rewrites. We don't even teach this section in our trainings and keeping it updated takes resources that we could use in more important topics. I'm pretty sure this section is outdated by now.

@yuri any thoughts?

**Comment by bennett000** [comment]
Joey updated this section before he left with all the latest work based on his real world experience.   That update has since been merged.  I'm going to close this issue for now.  If anyone objects we can reopen it and discuss.  I have no strong opinions about upgrades.
