### ISSUE TITLE
Update code examples

### ISSUE THREAD

**Issue by e-schultz** [rangle/ngCourse2#678]
* May need to break this down a bit more.
* Need to review book content for example code that is using outdated/deprecated features and/or syntax
* Update examples and plunkers - updates should probably start to conform to style guide and consistent naming conventions
* Exercises - TBD, as what Sean and Michael have done for UC Davis may remove the need for  them

**Comment by winkerVSbecks** [comment]
@e-schultz Router API changed slightly because of modules. I tracking those updates on card #696

**Comment by barretodavid** [comment]
Isn't this the same task as #692?

**Comment by winkerVSbecks** [comment]
@barretodavid no. The other card is for the `examples` and `exercises` directory in the repo. Whereas this card is for the code snippets and plunkers.

**Comment by winkerVSbecks** [comment]
- [ ] Bootstrapping 
- [ ] Components in Angular 2
- [ ] Directives
- [ ] Advanced Components
- [ ] Observables
- [ ] Change Detection
- [ ] Advanced Angular
- [ ] Dependency Injection (Michael is working on this)
- [ ] Pipes
- [ ] Forms (Sean is working on this)
- [x] Routing
- [ ] Redux and Ngrx
- [x] Testing 

@seanmay @barretodavid @e-schultz @bennett000  all these sections have examples that need to be updated to RC5.

**Comment by e-schultz** [comment]
Bootstrapping is updated (content + example) in #700 (issue) #701 (PR)

**Comment by e-schultz** [comment]
@seanmay when doing a quick overview of RC5/6 - updated the plunkers and a bit of content to be RC5/RC6. We have a bunch of 'unused' examples in the repo that we can probably remove,

**Comment by e-schultz** [comment]
@bennett000 noticed that the plunkers got updated for DI but not the examples in the repo, updated those for you so it should be done

**Comment by bennett000** [comment]
Thanks @e-schultz I completely forgot about that.
