### ISSUE TITLE
Add Course Section about Zones

### ISSUE THREAD

**Issue by smithad15** [rangle/ngCourse2#679]
Should probably add a module for ZoneJS under Advanced Angular that covers:
- What are zones (external library, monkey patch on Web APIs, integrated with the Event Loop, etc.)
- How Angular runs within it's own zone (ngZone) created at bootstrap
- Zone's integration into the change detection cycle including the use of ngZone.onMicrotaskEmpty
- Running code outside of the Angular zone for change detection performance improvements

**Comment by e-schultz** [comment]
Good point, I think basic understanding of zones is also important when integrating with 3rd party libraries and help cover 'how do I jQuery that?'

**Comment by smithad15** [comment]
How not to jQuery could be a section on its own 😄
