### ISSUE TITLE
jsPerf Examples Not Working (Remove Them)

### ISSUE THREAD

**Issue by smithad15** [rangle/ngCourse2#680]
jsPerf is down and seems to have been for over a year (since June 19, 2015 from the link provided on the site). This renders the examples related to ImmutableJS performance ( `12.1.4.4 Performance`, `12.1.4.5 Persistent and Transient Data Structures`) useless. Should probably find some other solution to communicate the performance impact of ImmutableJS.

**Comment by e-schultz** [comment]
Thinking we might be able to just remove these parts - jsPref is down (for how long?), and at this point - most people are already a bit brain-drained  - there is a rather large chunk on Immutable, that we then barely touch on, don't think it would hurt to slim down this section a little bit.

Thoughts @bennett000 @SethDavenport @seanmay ?

**Comment by jamesbs** [comment]
@bennett000 @e-schultz The suggestion here would be to remove the transient data structure section as a whole or just references to jsperf? I agree that it doesn't make sense to covert this material during client training but I think there's value in having this section for internal reference/skills development.

**Comment by bennett000** [comment]
@jamesbs IMO we'd just be removing the references to jsperf since it (AFAIK) no longer works
