### ISSUE TITLE
Update all forms to use Forms Module

### ISSUE THREAD

**Issue by winkerVSbecks** [rangle/ngCourse2#689]
Forms section
Other sections that use older module (Obsv, bootstrap, etc).

**Comment by bennett000** [comment]
@seanmay were you on this card?  This card might be a dupe? #639

**Comment by e-schultz** [comment]
* bootstrap section done

**Comment by gillianml** [comment]
@e-schultz Is this a duplicated issue?  If yes, please close.

**Comment by e-schultz** [comment]
this has been covered in other cards , closing this.
