### ISSUE TITLE
Update code examples: Components in Angular 2

### ISSUE THREAD

**Issue by kosz** [rangle/ngCourse2#703]

**Comment by kosz** [comment]
seems like nothing needs updating here

**Comment by rpdasilva** [comment]
What about the plunkers and code examples?
They're still on RC4 using the old bootstrap method (as well as npmcdn vs. unpkg)

**Comment by kosz** [comment]
@rpdasilva thanks for that hadn't realized there were working plunkers behind that code. I'll work on fixing those
