### ISSUE TITLE
Update ngrx section of eBook

### ISSUE THREAD

**Issue by gillianml** [rangle/ngCourse2#717]
In the August 31 Support Squad weekly meeting, Michael Bennett raised that it would be worthwhile for someone on the Support Squad to master ngrx and update the eBook accordingly.

AC:
- Show how to set up a store.

**Comment by SethDavenport** [comment]
The existing redux & ngrx section has several plunkrs implemented with both ng2-redux and ngrx

**Comment by SethDavenport** [comment]
some topics of potential interest: 

side effect handling with ngrx/effects vs ng2-redux + redux-observable

time travel able routing with ngrx/router vs ng2-redux-router

**Comment by gillianml** [comment]
@marcandrews if you're still interested in working on this, please add yourself to the card.

**Comment by egervari** [comment]
I could do this actually, at some point. I setup ngrx on Univeris and I also created my own side effects framework that worked with AoT

**Comment by egervari** [comment]
FYI, decorators and ngrx-effects does not work with aot.

**Comment by egervari** [comment]
This is now finished. I assigned Michael to review it :)
