### ISSUE TITLE
Update Code Examples to RC6

### ISSUE THREAD

**Issue by gillianml** [rangle/ngCourse2#720]
- [x] Bootstrapping (Philip)
- [x] Components in Angular 2 (Philip)
- [x] Directives (Philip)
- [x] Advanced Components (Philip)
- [x] Observables (Evan)
- [x] Change Detection (Philip)
- [x] Advanced Angular (Philip)
- [x] Dependency Injection (Michael)
- [x] Pipes (Philip)
- [x] Forms (Sean)
- [x] Routing (Philip)
- [x] Redux and Ngrx (Philip)
- [x] Testing (Philip)

**Comment by e-schultz** [comment]
@bennett000 looks like your DI stuff was already moved to RC6 anyways - just updated the code in the repo to match the plunker
@seanmay think I got the forms done when doing a pass-over of all of the RC5/6 stuff today

**Comment by bennett000** [comment]
Yes I did the RC6 updates at the same time.
