### ISSUE TITLE
Real World Examples

### ISSUE THREAD

**Issue by e-schultz** [rangle/ngCourse2#744]
To get better value and understanding of various Angular 2 features, having examples that mimic real-world scenarios and use cases that people have instead of contrived examples that feel forced to just show off the feature would be useful.

Review each section / example in the book, and identify if the example makes sense. If all of the examples in a section seem good / sensible - mark it as done or with a :+1:, if a section contains contrived examples, create a card to improve that example and mark it as :-1: blow. 

This card is to only identify where the work needs to be done, one all sections blow have been marked as :+1: or :-1: - it can be moved to done. 
- [x] Bootstrapping (Troy)
- [x] Directives (Alan Thai)
- [x] Advanced Components (Alan Thai) 
- [x] Dependency Injection (Troy)
- [x] Pipes (Alan Thai)

**Comment by gillianml** [comment]
@bennett000 Thanks for grooming the list above!
