### ISSUE TITLE
Internationalization (i18n)

### ISSUE THREAD

**Issue by e-schultz** [rangle/ngCourse2#745]
Details are starting to come out about localization, came across this example repo - https://github.com/StephenFluin/i18n-sample, looks like the official i18n solution is using the XILF file format

Basic details in this blog post: http://angularjs.blogspot.ca/2016/09/angular-2-rc6_1.html

AC:
- Section in book is added
- Explain what i18n is
- Describe how to use the official RC6+ i18n features 
- Use of the ng-xi18n tool
- Describe how to work with the XILF files and workflow for using it

Timebox: roughly 2 days for an MVP

**Comment by gillianml** [comment]
@kosz has been investigating and reading up on this subject, and hasn't written anything yet. Whomever picks up this card can reach out on slack if they have any questions.

**Comment by gillianml** [comment]
Un assigning @kosz as he has requested vacation day beginning today

**Comment by bennett000** [comment]
https://github.com/angular/angular.io/pull/2340  I haven't look at this yet but it will hopefully help

**Comment by gillianml** [comment]
@wzaghal will outline some bullet points then get review and then turn them into paragraphs.

**Comment by wzaghal** [comment]
So I've been using [this](https://angular.io/docs/ts/latest/cookbook/i18n.html#!#angular-i18n) as my primary learning resource:

These are the bullet-points/sections I thought we could add:

- Introduction
    - What is i18n ?
    - What is it's purpose?
    - Why is it useful/needed?

- Process & Roles
    - Who is involved?
    - What is the process if i18n?

- Tooling and Setup (with code samples)
    - What tools do we need?
    - How do these tools work?
    - What areas of code will we need to change/update?

- Setup (part 2 with code samples)
    - How do we merge the translation files that are translated?
    - What are the 2 different ways to do this? (AoT vs JiT)

Thoughts and criticisms are welcome.

**Comment by gillianml** [comment]
@wzaghal writes: "I was writing the AoT and JiT Compilation sections, only to realize I really should have some working examples on plnkr so that the users can actually see the code in action as opposed to just seeing code snippets. So today I’ll be working on creating those basic working i18n examples"

**Comment by barretodavid** [comment]
This is already solved by PR #791
