### ISSUE TITLE
Accessibility

### ISSUE THREAD

**Issue by e-schultz** [rangle/ngCourse2#746]
* Why accessibility is important
* What features angular2 has
* General HTML accessibility features/considerations
* How to design for accessibility

Timebox: Roughly 1 day

Section Outline
- [x] Intro
- [x] Why a11y
- [x] Key concerns
  - [x] Semantic Markup
  - [x] Keyboard Accessibility
  - [x] Visual Assistance
- [x] Manual Testing
  - [x] Screen readers
- [ ] Automated Testing (no longer part of MVP, Michael will make new cards)
  - [ ] Angular test methods
  - [ ] axe-core
- [x] Additional Resources

**Comment by gillianml** [comment]
@jamesbs working on some examples.  Add a checklist to this issue

**Comment by jamesbs** [comment]
The issue has been updated with a section outline. This card looks to be rather large and I may not be able to get all of the work on it done before I go on vacation so I'm hoping to deliver everything up to testing in one PR and testing sections can be done in further PRs.
