### ISSUE TITLE
Remove anti-pattern from code example for access_child_components_from_template

### ISSUE THREAD

**Issue by rajinder-yadav** [rangle/ngCourse2#820]
Under access_child_components_from_template:

Code example for 'app/my-example.component.ts'  is an anti-pattern, we should pass the form value rather than NgForm object to MyExampleComponent.

**Comment by jamesbs** [comment]
Any reason why this is an anti pattern? We have access to properties like NgForm.valid or can drill down into specific fields if we want to by passing in the form

**Comment by rajinder-yadav** [comment]
Yes! a function should not have to know how to grab the data it needs, this is tightly coupled code which is an anti-pattern. Simply pass the string required in this case.

**Comment by jamesbs** [comment]
Component classes are pretty tightly coupled to their templates though. It's not really any different than the class knowing how to resolve the structure of the form data (when using form.value). It's simply moving the property access away from the typescript class -> template (which is prone to typos and not statically analyzed).

**Comment by rajinder-yadav** [comment]
That's not an excuse to correct tightly coupled code in our function, right. For argument sake, say we had 100 functions that each took a form object when a simple value could have sufficed, then one day someone goes and changes up the form object on you. Now you have broken code in 100 places that need to be changed. If you simply passed in the value because you understand the evils of tightly coupled code, you would only need to fix this in one place where is getting pumped out. This example is very isolated & simple, still there is no excuse to use good coding practices. Just pass in what is needed, let's not teach others how to write code with anti-patterns and make them think tightly coupled code is a style to be followed.

You ask me to explain and now you're defending the anti-pattern?

**Comment by rajinder-yadav** [comment]
Also want to make a correction with what you said, the component class and template have a relationship between each other, this is different than saying there are tightly coupled. You still need to pass data from the template to the class. When you pass in the form object, at this point you're explicitly making the code tightly coupled. The class does not have direct access to the template reference variable or it's DOM elements, they are either passed in or bound to using a decorator like `@ViewChild`.

**Comment by jamesbs** [comment]
Had a discussion with @rajinder-yadav and although we're not in full agreement on the approach we've come to an understanding regarding this issue.
