### ISSUE TITLE
Blog link in header is dead

### ISSUE THREAD

**Issue by jamesbs** [rangle/ngCourse2#854]
Link in https://github.com/rangle/gitbook-plugin-theme-rangle-io matches the book's protocol(https) but the rangle blog doesn't load on https

**Comment by bennett000** [comment]
This is an `https` breakage, it's actually in my domain and @bertrandk

**Comment by bertrandk** [comment]
Made a PR to change the [link in the header](https://github.com/rangle/gitbook-plugin-theme-rangle-io/pull/1). Having the blog support HTTPS has is more involved and has a larger testing burden. The move is in the works but probably will occur simultaneously with an infrastructure migration.

**Comment by bertrandk** [comment]
The new header is available on NPM. It may require a re-publish to take effect.

/cc @bennett000

**Comment by bennett000** [comment]
amazing.  Thanks Bertrand!

**Comment by bennett000** [comment]
*NOTE* there is no PR against this repo for this because the header is included separately.  We will know if this is working on the next merge.  If the blog link works we will have to manually close this card then.

**Comment by bennett000** [comment]
This is verified to be working
