### ISSUE TITLE
Create outline of chapter on optimizing development workflow using Docker

### ISSUE THREAD

**Issue by gvwilson** [rangle/ngCourse2#906]
For architect's guide

**Comment by darrenmce** [comment]
Outline:

 - Overview of modern distributed web applications (client app, api, cache, database)
 - Challenges of local development with this architecture
    - issues with connecting to remote "test" servers 
    - issues with local running dependencies
 - ![image](https://cloud.githubusercontent.com/assets/1863428/25623749/ab23443c-2f25-11e7-958a-ab854c6b1145.png) (virtualization)
    - VMs, Vagrant & _**Docker**_

 - Brief intro into docker
   - basics
   - volume mounting
   - networking and port binding
   - docker-compose

 - Example with angular (client app), express (api), redis (cache).
   - setting up angular a dev flow to work with a local docker-composed api/cache layer
   - touch on how easy it would be to add a mongo or postgres db as well
