### ISSUE TITLE
Update - Introduction

### ISSUE THREAD

**Issue by AbdellaToronto** [rangle/ngCourse2#936]
## Introduction

- [ ] http://ngcourse-1.rangle.io link does not work
- [ ]  https://www.gitbook.com/book/rangle-io/ngcourse2/discussions link leads to the main gitbook page

**Comment by magz99** [comment]
hi @AbdellaToronto for this ticket, I would remove the link to the ng1 book completed, and just figure out how to re-link to the GitHub book discussions?
